### ISSUE TITLE
Checking commit log based on version code

### ISSUE THREAD

**Issue by DumbDev168** [rubiconba/fastlane-plugin-flutter-version-manager#12]
How to check git log based on version: 1.0.5+77326735 ?

Is this `77326735` a unix timestamp?
I tried this. But it seems this package has some offset set?

`git log --date=unix --before=1635020939 --after=1635020939 --pretty=format:"%h"`

**Comment by davormaricdev** [comment]
It is, but it has the offset of [1598622000](https://github.com/rubiconba/fastlane-plugin-flutter-version-manager/blob/master/lib/fastlane/plugin/flutter_version_manager/actions/flutter_version_manager_action.rb#L6) due to max version number constraints of Google Play Store Console

**Comment by DumbDev168** [comment]
Thanks for reply. Let's me close this.
