### ISSUE TITLE
How to increase the version code by one and not use the git hash?

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [rubiconba/fastlane-plugin-flutter-version-manager#6]
I used 
```
lane :bump_patch do
  flutter_version_manager(
    arguments: "-patch",
    yml: "./version.yml",
    pubspec: "./example_pubspec.yaml")
end
```
to only bump patch and not to have a huge number as version code. Instead, can we just increase the version code by 1?

**Comment by davormaricdev** [comment]
You can do it manually, however, that defeats the whole purpose of this library which is not carrying about version code at all.
