### ISSUE TITLE
how to bump code version 

### ISSUE THREAD

**Issue by francescopetrungaro** [rubiconba/fastlane-plugin-flutter-version-manager#7]
I would like to bump code version.
Example from 1.0.0+1 to 1.0.0+2

How can I do that?

**Comment by davormaricdev** [comment]
Bumping code version happens automatically behind the scenes when you use `apply` argument. Version is picked up from the timestamp of head commit and reduced by a [hardcoded value](https://github.com/rubiconba/fastlane-plugin-flutter-version-manager/blob/a33d1362196b7de6ea1ae779d855b444c8c00873/lib/fastlane/plugin/flutter_version_manager/actions/flutter_version_manager_action.rb#L6)

```
lane :apply_new_version do
  flutter_version_manager(
    arguments: "-apply",
    yml: "./version.yml",
    pubspec: "./example_pubspec.yaml")
end
```
