### ISSUE TITLE
New version deletes build number

### ISSUE THREAD

**Issue by talbiislam96** [rubiconba/fastlane-plugin-flutter-version-manager#9]
thank you so much for your help it worked , but the version was : 1.0.0+2 when I applied bump-patch it became like this : 0.0.2+51144791 , this is not what I want to happen I want to keep the build number (after the plus sign ) also keep the major /minor only bump patch !

**Comment by davormaricdev** [comment]
Hey @talbiislam96. 
Make sure that `version.yml` has major assigned to 1, minor to 0 and patch to 0. That way, when `bumpPatch` is called, new version should be `1.0.1`.
Build number is automatically incremented. Providing alternate way of incrementing build number defeats the core concept of this plugin.

See:

#7 
#6

**Comment by talbiislam96** [comment]
@davormaricdev I get it , is it possible to use sha instead of commit timestamp?

**Comment by davormaricdev** [comment]
There are no plans on adding alternate way of referencing build number at the current time @talbiislam96
